aggregator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
]

content/urls.py
from django.urls import path
from .views import (
    index,
    view_articles,
    view_news
)

app_name = "content"

urlpatterns = [
    path('', index, name="index"),
    path('articles/', view_articles, name="view_articles"),
    path('news/', view_news, name="view_news")
]

content/models.py
from django.db import models

# Create your models here.
class RealStateNews(models.Model):
    title = models.CharField(max_length=200, primary_key=True)
    url = models.URLField(max_length=100)
    author = models.CharField(max_length=30)
    date = models.DateField()

    def __str__(self):
        return self.title

class RealStateArticle(models.Model):
    title = models.CharField(max_length=200, primary_key=True)
    url = models.URLField(max_length=100)
    author = models.CharField(max_length=30)
    date = models.DateField()

    def __str__(self):
        return self.title

content/forms.py
from django import forms

class ModalForm(forms.Form):
    author_name = forms.CharField(label="Author Name", 
                                    max_length=40, 
                                    required=False)
    date = forms.DateField(label="Date", 
                            widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),
                            required=False
                        )

content/views.py
from django.shortcuts import render
from .models import RealStateArticle
from .models import RealStateNews
from .forms import ModalForm

# Create your views here.
def index(request):
    return render(request, 'content/index.html')


def view_articles(request):
    """
        View Articles View
    """
    # getting all data here
    querysets = RealStateArticle.objects.all()

    if 'author_name' in request.GET and 'date' in request.GET:
        author_name = request.GET.get('author_name')
        date_ = request.GET.get('date')

        if author_name:
            querysets = querysets.filter(author__contains=author_name).all()
        if date_:
            querysets = querysets.filter(date=date_).all()
    
    context = {
        "querysets" : querysets,
        'content_type' : 'Articles',
        'form' : ModalForm()
    }
    
    return render(request, 'content/view_data.html', context)


def view_news(request):
    """
        View News View
    """

    # getting all data here
    querysets = RealStateNews.objects.all()

    if 'author_name' in request.GET and 'date' in request.GET:
        author_name = request.GET.get('author_name')
        date_ = request.GET.get('date')

        if author_name:
            querysets = querysets.filter(author=author_name).all()
        if date_:
            querysets = querysets.filter(date=date_).all()
    
    context = {
        'querysets' : querysets,
        'content_type' : 'News',
        'form' : ModalForm()
    }
    return render(request, 'content/view_data.html', context)

templates/content/index.html
<link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<nav class="navbar navbar-dark bg-dark">
    <div class="col-md-10">
        <a class="navbar-brand" href="{% url 'content:index' %}">
            <u>Welcome to the Content Aggregator</u>
        </a>
    </div>
</nav> 

<br>
<div class="ml-3">
    <h4>What do you want to see?</h4>
    <h5>
        i)
        <a href="{% url 'content:view_news' %}">News</a>
    </h5>
    <h5>
        ii)
        <a href="{% url 'content:view_articles' %}">Articles</a>
    </h5>
</div>

templates/content/view_data.html
<link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<style>
    body {
        overflow-x: hidden;
    }
    .even{
        background-color: #d01b1b3b;
    }
    .odd{
        background-color: #0000002e;
    }
</style>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form action="">
                    {{ form.as_p }}
                    <p style="color: brown">
                        Note: If you want to use only one of them let the other be blank and submit.
                    </p>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-dark bg-dark">
    <div class="col-md-10">
        <a class="navbar-brand" href="{% url 'content:index' %}">Real Estate {{ content_type }}</a>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Filter {{ content_type }}
          </button>
    </div>
</nav> 

{% if querysets %}
    <div class="row">
        {% for query in querysets %}
            <div class="col-sm-3 card {% cycle 'even' 'odd' %}">
                <p><a href="{{query.url}}" target="_blank">{{ query.title }}</a></p>
                <p>
                    <span style="float: left;">{{ query.author }}</span>
                <span style="float: right;">{{ query.date }}</span>
                </p>
            </div>
        {% endfor %}
    </div>
    
{% endif %}

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>